spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/market
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db-changelog-master.xml